apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://community-charts.github.io/helm-charts"
    targetRevision: 1.8.1
    chart: mlflow
    helm:
      valuesObject:
        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: false
          auth:
            username: mlflow
            password: mlflowpass
            database: mlflowdb
        backendStore:
          databaseMigration: true
          databaseConnectionCheck: true
        artifactRoot:
          defaultArtifactRoot: "./mlruns"
          defaultArtifactsDestination: "./mlartifacts"
        auth:
          enabled: false
        service:
          type: ClusterIP
          port: 80
          containerPort: 5000
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true